### PR TITLE
fix(chart.tooltip function): replaced : chart.tooltip.Content with

### PR DESCRIPTION
**Pull request by aniketmaithani**
- chart.tooltip.contentGenerator
- ref : `http://stackoverflow.com/questions/35125110/django-nvd3-chart-tooltipcontent-is-not-a-function

### CODE REVIEW

**Comment by areski** [comment]
related to #128, #118 and #124 
There is some work in progress as you can see here:
https://github.com/areski/python-nvd3/pull/128/files
So you might want to create your pull request against the branch `nvd3-1.8`

**Comment by alaalqadi** [comment]
@areski pleas merge this as i need to reflect the chart.tooltipContentGenerator changes ASAP please

**Comment by daadu** [comment]
@aniketmaithani changing `chart.tooltipContentGenerator` -> `tooltip.contentGenerator` is half of the problem solved, the arguments in the callback function have changed from `function(key, y, e, graph)` to `function(d, elem)`

Check this: https://github.com/novus/nvd3/blob/447cce8c180a92fcabd571cca410760deb3a2c1d/src/tooltip.js#L60 in nvd3

**Comment by areski** [comment]
Fixed by #166

**Pull request closed without merging**
