### PR TITLE
Nvd3 1.8

### PR DESCRIPTION
**Pull request by jojolalpin**
As required, replacements in templates of chart.tooltipContent to chart.tooltip.contentGenerator

### CODE REVIEW

**Comment by areski** [comment]
but the function changed http://nvd3-community.github.io/nvd3/examples/documentation.html#tooltip

**Comment by jojolalpin** [comment]
Sorry, I made changes as explained in an issue and it made the piechart example work so I made the PR to help. As you requested, I tried the same on 1.8 instead of develop without thinking.

**Comment by areski** [comment]
Something is weird, cause on 1.7 the old method `tooltipContent` is supported so I dont see why it needed to be fixed there

**Comment by areski** [comment]
Thanks for the fix

**Pull request merged**
